spring:
  application:
    name: shoplace-backend
  datasource:
    url: jdbc:sqlite:shoplace.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true